# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import subprocess

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(899, 269)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(20, 50, 161, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.pastetext)

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(20, 10, 851, 31))
        self.textEdit.setObjectName("textEdit")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 50, 161, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.download)

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 100, 261, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.getQuality)

        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 140, 104, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(140, 140, 104, 31))
        self.textEdit_3.setObjectName("textEdit_3")

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 190, 331, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.quality_download)

        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(380, 130, 491, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.clicked.connect(self.download_playlist)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 899, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Paste video url from Clipboard"))
        self.pushButton_2.setText(_translate("MainWindow", "Download video in Best Quality"))
        self.pushButton_3.setText(_translate("MainWindow", "Get Quality"))
        self.pushButton_4.setText(_translate("MainWindow", "Download at Input Quality"))
        self.pushButton_5.setText(_translate("MainWindow", "Download PlayList"))

    def pastetext(self):
        self.textEdit.setText(clipboard.text())

    def download(self):
        link = str(self.textEdit.toPlainText())
        quality = "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]"
        subprocess.run(["ytdlp.exe", "-f", quality, link, "--add-metadata", "--embed-subs"])

    def getQuality(self):
        link = str(self.textEdit.toPlainText())
        subprocess.run(["ytdlp.exe", "-F",  link])

    def quality_download(self):
        link = str(self.textEdit.toPlainText())
        video = str(self.textEdit_2.toPlainText())
        audio = str(self.textEdit_3.toPlainText())
        quality = video+"+"+audio
        subprocess.run(["ytdlp.exe", "-f", quality, link, "--add-metadata", "--embed-subs"])

    def download_playlist(self):
        link = str(self.textEdit.toPlainText())
        subprocess.run(["ytdlp.exe", "-o", '%(playlist)s/%(playlist_index)s - %(title)s.%(ext)s', "-f", "bv*[ext=mp4]+ba[ext=m4a]/b[ext=mp4]", link, "--add-metadata", "--embed-subs"])




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    clipboard = app.clipboard()
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
